name: Release

on:
  push:
    branches:
      - main

jobs:
  call-build:
    uses: ./.github/workflows/build.yml
    
  bump-tag:
    name: Bump Tag
    needs: call-build
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.tag_version.outputs.new_tag }}
    steps:
      - uses: actions/checkout@v3
      - name: Github tag bump
        id: tag_version
        uses: anothrNick/github-tag-action@1.66.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: false
          DEFAULT_BUMP: patch
          MAJOR_STRING_TOKEN: "major"
          MINOR_STRING_TOKEN: "feat"
          PATCH_STRING_TOKEN: "fix"
          
  release:
    name: Release
    needs: [call-build, bump-tag]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: firmware
          
      - name: Rename firmware file
        run: mv firmware.bin firmware-${{ needs.bump-tag.outputs.new_tag }}.bin
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.bump-tag.outputs.new_tag }}
          files: firmware-${{ needs.bump-tag.outputs.new_tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
