name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_release:
    name: Build Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'
      - name: Show python version
        run: python --version
      - name: Install PlatformIO
        run: python -m pip install -U platformio
      - name: Build firmware
        run: platformio run
        id: version
      - name: Archive
        uses: actions/upload-artifact@v3
        with:
          name: firmware
          path: .pio/build/*/firmware.bin
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: test
          files: firmware/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
