name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
          architecture: 'x64'
      - name: Show python version
        run: python --version
      - name: Install PlatformIO
        run: python -m pip install -U platformio
      - name: Build firmware
        run: platformio run
        id: version
      - name: Github tag bump
        id: tag_version
        uses: anothrNick/github-tag-action@1.66.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          WITH_V: false
          MINOR_STRING_TOKEN: feat
          PATCH_STRING_TOKEN: fix
      - name: Rename output file
        run: mv .pio/build/esp-wrover-kit/firmware.bin .pio/build/esp-wrover-kit/firmware-${{ steps.tag_version.outputs.new_tag }}.bin
      - name: Assign file name to env
        run: |
          FILENAME=.pio/build/esp-wrover-kit/firmware-${{ steps.tag_version.outputs.new_tag }}.bin
          echo $FILENAME
          echo "FILENAME=$FILENAME" >> $GITHUB_ENV
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          files: ${{ env.FILENAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
