name: Release

on:
  push:
    branches:
      - main

jobs:
  build_release:
    name: Build Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
          architecture: 'x64'
      - name: Show python version
        run: python --version
      - name: Install PlatformIO
        run: python -m pip install -U platformio
      - name: Build firmware
        run: platformio run
        id: version
      - name: Github Tag Bump
        id: tag_version
        uses: anothrNick/github-tag-action@1.66.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: false      
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          files: .pio/build/*/firmware-${{ steps.tag_version.outputs.new_tag }}.bin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
